<?php

use function Livewire\Volt\{title};

title('Msgraph - Übersicht');

?>

<x-intranet-app-msgraph::msgraph-layout heading="Msgraph App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-msgraph::msgraph-layout>